# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nintendo 64 games, news, accessories | N64 Blog
email: n64blog@gmail.com
description: Indulge your nostalgia for the Nintendo 64 by exploring the console's games, hardware and peripherals. Includes latest N64 news.
keywords: "n64 blog, nintendo 64, n64, n64 games, n64 website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://n64blog.com" # the base hostname & protocol for your site
twitter_username: n64blog
github_username:  n64blog

# Build settings
markdown: kramdown

collections:
  games:
    output: true
